### ISSUE TITLE
IcStepper variant causing ResizeObserver loop runtime error in React

### ISSUE THREAD

**Issue by wendycocksedge** [mi6/ic-design-system#832]
## Summary of the bug

When using the ICStepper component in React ( the default variant) it seems to throw this uncaught runtime error when you try to resize the page:

ERROR
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3000/static/js/bundle.js:70113:58)
    at http://localhost:3000/static/js/bundle.js:70132:7

Is this a known issue?  The compact variant seems to work fine when re-sizing the browser window. 

## 🪜 How to reproduce

This is happening in a development project, but seems to happen whilst resizing the browser, which makes the IcStepper component swap from using the full width version to the compact version. 

## 📸 Screenshots or code

![image](https://github.com/mi6/ic-design-system/assets/160885243/023d2d46-2121-4703-86a8-5ae6202a443b)

## 🖥 📱 Device

- Type: Desktop
- Device: Windows
- Browser version:  Chrome Version 121.0.6167.187 (Official Build) (64-bit)

## 🧐 Expected behaviour

Not to throw the runtime error.

**Comment by GCHQ-Developer-299** [comment]
Hi @wendycocksedge - I've spun up a React app and stuck the below Stepper example into it. When i resize the page I don't experience any issues.
```js
<IcStepper>
                <IcStep stepTitle="Order coffee" stepType="completed" />
                <IcStep stepTitle="Pay for order" stepType="current" />
                <IcStep stepTitle="Collect" stepType="disabled" />
</IcStepper>
```

Are you able to provide more information about the issue you're having - which version of the ICDS packages have you got installed? And could you provide a code snippet showing the setup of your stepper?

Many thanks :)
